
# Site settings
encoding: utf-8
url: "http://danielwisky.com.br"
baseurl: ""
force-https: True

# HTML Head
lang: "pt-BR"
title: "Daniel Wisky"

copyright_name: "Daniel Wisky"
description: "site pessoal"

favicon: "/img/favicon.ico"
header-img: img/default-bg.jpg

# Social Buttons
disqus-shortname : "danielwisky"
github-username  : "danielwisky"
linkedin-url     : "https://br.linkedin.com/in/danielwisky"
email-username   : "daniel-ddw@hotmail.com"
youtube-username : "UClrHl2MtxbvaIRXte8Ehr-w"

# Google Analytics
google-tracking-id: "UA-41281548-2"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["LICENSE", "README.md"]

# Enable minification SASS
sass:
  style: compressed

plugins: [jekyll-paginate, jekyll-feed]
