title: Daniel Wisky
email: daniel-ddw@hotmail.com
description: "Conteúdos sobre Desenvolvimento e Tecnologia"
baseurl: ""
url: https://danielwisky.com.br
lang: pt-BR

sass:
  style: compressed

# output options (more information on Jekyll's site)
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate_path: "/page/:num/"
paginate: 10

kramdown:
  input: GFM

# fill in your Google Analytics ID to track your website using Google Analytics
google_analytics: "G-R9ZHFE3RQ5"

# to use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
disqus: "danielwisky"

# --- footer social media links --- #
social-network-links:
  - name: "RSS"
    url: "https://danielwisky.com.br/feed.xml"
    icon: "fas fa-rss"
  - name: "Me mande um e-mail"
    url: "mailto:daniel-ddw@hotmail.com"
    icon: "fas fa-envelope"
  - name: "GitHub"
    url: "https://github.com/danielwisky"
    icon: "fab fa-github"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/danielwisky"
    icon: "fab fa-linkedin"
  - name: "YouTube"
    url: "https://www.youtube.com/c/DanielWisky"
    icon: "fab fa-youtube"

# archives
jekyll-archives:
  enabled:
    - categories
  layout: 'archive'
  permalinks:
    category: '/categorias/:name/'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md